# Site settings
title: Sean Boyer's Profile
description: Sean Boyer's Profile
#baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "github.com/ashkore" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sean Boyer
user_description: I graduated college in December 2016 with a degree in Computer Information Systems and Security, during my free time i dabbled in programming, security and system administration.
user_title: Software Developer
email: SeanABoyer@gmail.com
#twitter_username: lorem_ipsum
github_username:  Ashkore
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
